import 'package:rick_morty_01/data/view/episode_model.dart';

List<EpisodeModel> episodesList = [
  EpisodeModel(
    episodeId: 1,
    episodeNum: 1,
    episodeName: "Пилот",
    episodePremierDate: "2 декабря 2013",
    episodeSeason: 1,
    episodeScreen: "assets/images/episodes/e_1.png",
    episodeDesc: 'Зигерионцы помещают Джерри и Рика в симуляцию, чтобы узнать секрет изготовления концен-трирован- ной темной материи.',
  ),
  EpisodeModel(
    episodeId: 2,
    episodeNum: 2,
    episodeName: "Пёс-газонокосильщик",
    episodePremierDate: "9 декабря 2013",
    episodeSeason: 1,
    episodeScreen: "assets/images/episodes/e_2.png",
    episodeDesc: '2 - Зигерионцы помещают Джерри и Рика в симуляцию, чтобы узнать секрет изготовления концен-трирован- ной темной материи.',
  ),
  EpisodeModel(
    episodeId: 3,
    episodeNum: 3,
    episodeName: "Анатомический парк",
    episodePremierDate: "16 декабря 2013",
    episodeSeason: 1,
    episodeScreen: "assets/images/episodes/e_3.png",
    episodeDesc: '3 - Зигерионцы помещают Джерри и Рика в симуляцию, чтобы узнать секрет изготовления концен-трирован- ной темной материи.',
  ),
  EpisodeModel(
    episodeId: 4,
    episodeNum: 4,
    episodeName: "М. Найт Шьямал-Инопланетяне!",
    episodePremierDate: "13 января 2014",
    episodeSeason: 1,
    episodeScreen: "assets/images/episodes/e_4.png",
    episodeDesc: '4 - Зигерионцы помещают Джерри и Рика в симуляцию, чтобы узнать секрет изготовления концен-трирован- ной темной материи.',
  ),
  EpisodeModel(
    episodeId: 5,
    episodeNum: 5,
    episodeName: "Мисикс и разрушение",
    episodePremierDate: "20 января 2014",
    episodeSeason: 1,
    episodeScreen: "assets/images/episodes/e_5.png",
    episodeDesc: '5 - Зигерионцы помещают Джерри и Рика в симуляцию, чтобы узнать секрет изготовления концен-трирован- ной темной материи.',
  ),
  EpisodeModel(
    episodeId: 6,
    episodeNum: 6,
    episodeName: "Напиток Рика №9",
    episodePremierDate: "20 января 2014",
    episodeSeason: 1,
    episodeScreen: "assets/images/episodes/e_6.png",
    episodeDesc: '6 - Зигерионцы помещают Джерри и Рика в симуляцию, чтобы узнать секрет изготовления концен-трирован- ной темной материи.',
  ),
  EpisodeModel(
    episodeId: 7,
    episodeNum: 7,
    episodeName: "Воспитание Газорпазорпа",
    episodePremierDate: "20 января 2014",
    episodeSeason: 1,
    episodeScreen: "assets/images/episodes/e_7.png",
    episodeDesc: '7 - Зигерионцы помещают Джерри и Рика в симуляцию, чтобы узнать секрет изготовления концен-трирован- ной темной материи.',
  ),
];
